### ISSUE TITLE
Possible Breaking changes to make

### ISSUE THREAD

**Issue by Dr-Emann** [RoaringBitmap/croaring-rs#108]
It seems we want to [do some breaking changes](https://github.com/saulius/croaring-rs/pull/106#discussion_r1236806925)

Trying to use this as a list of possible breaking changes we might want to make

- [x] Refactor Serialization for Bitmaps and Treemaps to use traits like in #106.

   Should we also try to future proof ourselves to have a `ViewDeserializer` vs `UncheckedViewDeserializer` (I'm expecting a safe view function at some point) 
- [x] I would love to change `Bitmap/Treemap::create` to `Bitmap/Treemap::new`, to match usual rust types
- [x] Likewise, `create_with_capacity` -> `with_capacity` (like [`Vec`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.with_capacity))

**Comment by Dr-Emann** [comment]
Maybe `From::from` rather than `Bitmap::of`? (so `Bitmap::from(&[0, 1, 2])` rather than `of`)

**Comment by andreas** [comment]
> Should we also try to future proof ourselves to have a `ViewDeserializer` vs `UncheckedViewDeserializer` (I'm expecting a safe view function at some point)

I've looked into providing a safe view deserialization function in CRoaring. My intention was to add two checks:

1) Guard against buffer overflows. This is fairly easy, though a bit cumbersome.
2)Validate alignment. My assumption was that if the input buffer was aligned, then all accesses would be aligned. Unfortunately this turned out not to be true. Because the `runFlagBitset` in the header has a variable number of bytes, this can cause unaligned accesses, even if the input buffer is aligned.

Unfortunately I don't see a good way of solving (2) without changing the spec, e.g. padding `runFlagBitset` to ensure alignment. As such, I don't think we should hold our breath on a safe view function (though I'd love to see it!) 😢

---

Generally speaking, I'd love to see a 1.0 release. My motivation is to use `croaring` via `plrust` in AWS RDS Postgres. I believe the next RDS `plrust` release is 1-3 months away, and I'd love to see `croaring` v1.0 supported rather than v0.9. That being said, I acknowledge that breaking changes should not be rushed. If I can help, let me know 😊

**Comment by Dr-Emann** [comment]
Thinking we might want to add the ability to serialize into any writer so we don't necessarily need to keep it all in memory. We'll probably want both into any writer, and into a Vec, since for Frozen we need to ensure alignment, and we can't do that with an arbitrary writer.

**Comment by anacrolix** [comment]
Is there a view from bytes for treemaps?

**Comment by Dr-Emann** [comment]
No, sorry, I'm still not being clear, just to avoid _two_ copies on the heap, you could *deserialize* from a file backed mmap, but there's not currently a way of creating a view for treemaps over an existing byte slice.
