### ISSUE TITLE
croaring 2.0 yanked?

### ISSUE THREAD

**Issue by damageboy** [RoaringBitmap/croaring-rs#136]
Hi,
It seems like the officially tagged release is 2.0 while this is the situation on crates.io:

![image](https://github.com/RoaringBitmap/croaring-rs/assets/125730/c3ac8da0-2979-4de2-9fc4-2a1e162f89b1)

Can someone from the project provide a clarification of the state of 2.0, is it brandishing a croaring 3.0 / 4.0 and what is exactly the release status.

Also, I personally think it would greatly add / improve clarity of the versioning would follow croraring major versioning at the least so that users clearly understand what they are getting...

**Comment by saulius** [comment]
Sorry for the misunderstanding @damageboy , there's [a critical issue](https://github.com/RoaringBitmap/CRoaring/issues/635) in CRoaring that made us yank the 2.0 release. Since there's a fix pr, I expect it will get merged soon and we can release `2.x` version of `croaring-rs` with a fix. 

In terms of versioning - new major version is released whenever there is a breaking change.

**Comment by Dr-Emann** [comment]
Version 2.0.2 is [on crates.io now](https://crates.io/crates/croaring/2.0.2) as the first non-yanked 2.x croaring-rs release.

I've hopefully clarified in the [README](https://github.com/RoaringBitmap/croaring-rs/blob/master/README.md#croaring-version) to both include the version of CRoaring we build with, and to explain why we don't match the major version (because breaking changes in CRoaring have often _not_ required breaking changes in the idiomatic rust bindings).

However, we _are_ now mirroring the CRoaring version in the [croaring-sys](https://crates.io/crates/croaring-sys/versions) crate.
