### ISSUE TITLE
build fails on 2.0.3

### ISSUE THREAD

**Issue by tzachar** [RoaringBitmap/croaring-rs#156]
the following line fails on rust 1.81: https://github.com/RoaringBitmap/croaring-rs/blob/f75467c1e6e5ac15d654dc2be4a6a85f36b6e706/croaring-sys/build.rs#L11

there should be a '&' before the `format!`:
```rust
build.flag_if_supported(&format!("-march={target_arch}"));
```

**Comment by Dr-Emann** [comment]
The problem is that `build.flag_if_supported` was changed to support owned and borrowed strings in `cc` version `1.1`, but `coraring-sys` incorrectly claimed it only needed at least `cc` version `1.0`. You should be able to `cargo update` your cc version to something > `1.1`, or the newest croaring-sys (published today) now correctly identifies the minimal `cc` version it requires.

See #149, which updated the minimal `cc` version, but today is the first `croaring-sys` publish since that change.

**Comment by tzachar** [comment]
10x.
Did a `cargo update`, which solved the issue.
